window:
  dimensions:
    columns: 160
    lines: 40
  position:
    x: 100
    y: 100
  padding:
    x: 10  
    y: 1
  dynamic_padding: false
  opacity: 0.95
  title: Terminal

font:
  normal:
    family: FiraCode Nerd Font
  size: 14

live_config_reload: true